
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/postgres
    username: postgres
    password: test


logging:
  level:
    org.hibernate.SQL: DEBUG